# Generated by Django 2.2.4 on 2019-09-17 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetail',
            new_name='StudentDetails',
        ),
    ]
