# Generated by Django 2.2.4 on 2019-08-28 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fc_common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=255)),
                ('entity_id', models.IntegerField()),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('business_activity', models.CharField(max_length=255)),
                ('iec', models.CharField(max_length=30)),
                ('gst', models.CharField(max_length=30)),
                ('pan', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=30)),
                ('company_bio', models.TextField()),
                ('company_structure', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_logistic_spend_currency', models.CharField(max_length=255)),
                ('annual_logistic_spend', models.BigIntegerField()),
                ('annual_air_shipments', models.IntegerField()),
                ('annual_lcl_shipments', models.IntegerField()),
                ('annual_fcl_shipments', models.IntegerField()),
                ('total_shipments', models.IntegerField()),
                ('annual_air_volume', models.IntegerField()),
                ('annual_lcl_volume', models.IntegerField()),
                ('annual_fcl_volume', models.IntegerField()),
                ('incorporation_year', models.IntegerField()),
                ('incorporation_number', models.IntegerField()),
                ('annual_revenue_currency', models.CharField(max_length=5)),
                ('annual_revenue', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCountries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fc_cust_reg.Addresses')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fc_cust_reg.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fc_cust_reg.CompanyDetails'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fc_common.Documents'),
        ),
    ]
