# Generated by Django 2.2.4 on 2019-08-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='lanuch_date',
            new_name='launch_date',
        ),
    ]
