# Generated by Django 2.2.4 on 2019-08-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_heading',
            new_name='heading',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_id',
            new_name='id',
        ),
    ]
